# Generated by Django 2.2.7 on 2020-02-04 12:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ref_pages', '0004_auto_20200203_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='referer',
            name='title_link',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
